package com.example.myjavafxquizgame;

public class Aqidah{
    static String [][] option = {
            {"4", "5", "6", "7"},
            {"1", "2", "3", "4"},
            {"1", "2", "3", "4"},
            {"1", "2", "3", "4"},
            {"1", "2", "3", "4"},
            {"2", "3", "4", "5"},
            {"3", "4", "5", "6"},
            {"20", "25", "30", "35"},
            {"Nabi Muhammad SAW", "Nabi Isa AS", "Nabi Daud AS", "Nabi Musa AS"},
            {"1", "3", "5", "7"},
            //10
            {"8", "10", "12", "15"},
            {"Mengatur rezeki dan menurunkan hujan atas perintah Allah", "Menjaga pintu surga", "Menyampaikan wahyu", "Mencatat amal baik"},
            {"Mengatur rezeki dan menurunkan hujan atas perintah Allah", "Menjaga pintu surga", "Menyampaikan wahyu", "Mencatat amal baik"},
            {"Mengatur rezeki dan menurunkan hujan atas perintah Allah", "Meniup trompet sangkakala", "Menyampaikan wahyu", "Mencatat amal baik"},
            {"Mengatur rezeki dan menurunkan hujan atas perintah Allah", "Menjaga pintu surga", "Menyampaikan wahyu", "Mencabut nyawa"},
            {"Mengatur rezeki dan menurunkan hujan atas perintah Allah", "Menjaga pintu surga", "Menanyai manusia di alam kubur", "Mencatat amal baik"},
            {"Mencatat amal baik", "Mencatat amal buruk", "Menyampaikan wahyu", "Mencabut nyawa"},
            {"Mencatat amal baik", "Mencatat amal buruk", "Menyampaikan wahyu", "Mencabut nyawa"},
            {"Mencatat amal baik", "Menjaga Neraka", "Menjaga Surga", "Mencabut nyawa"},
            {"Mencatat amal baik", "Menjaga Neraka", "Menjaga Surga", "Mencabut nyawa"},
            //20
            {"Nabi Musa AS", "Nabi Isa AS", "Nabi Muhammad SAW", "Nabi Daud AS"},
            {"Nabi Musa AS", "Nabi Isa AS", "Nabi Muhammad SAW", "Nabi Daud AS"},
            {"Nabi Musa AS", "Nabi Isa AS", "Nabi Muhammad SAW", "Nabi Daud AS"},
            {"Nabi Musa AS", "Nabi Isa AS", "Nabi Muhammad SAW", "Nabi Daud AS"},
            {"Nabi Musa AS", "Nabi Isa AS", "Nabi Muhammad SAW", "Nabi Daud AS"},
            {"Nabi Musa AS", "Nabi Isa AS", "Nabi Muhammad SAW", "Nabi Daud AS"},
            {"Nabi Musa AS", "Nabi Ibrahim AS", "Nabi Muhammad SAW", "Nabi Daud AS"},
            {"Nabi Musa AS", "Nabi Isa AS", "Nabi Muhammad SAW", "Nabi Daud AS"},
            {"Nabi Musa AS", "Nabi Isa AS", "Nabi Muhammad SAW", "Nabi Sulaiman AS"},
            {"Nabi Musa AS", "Nabi Isa AS", "Nabi Muhammad SAW", "Nabi Daud AS"},
            //30
            {"Kiamat Kubra", "Kiamat halus", "Kiamat ringan", "Kiamat kecil"},
            {"Kematian", "Keluarnya dajjal", "Tsunami", "Tanah longsor"},
            {"Kematian", "Keluarnya dajjal", "Turunnya Nabi Isa AS", "Yajuj dan Majuj"},
            {"Kematian", "Keluarnya dajjal", "Turunnya Nabi Isa AS", "Yajuj dan Majuj"},
            {"Musnahnya alam semesta", "Tsunami", "Kematian", "Gempa bumi"},
            {"Hisab", "Mizan", "Ba'ts", "Jaza"},
            {"Hisab", "Mizan", "Ba'ts", "Jaza"},
            {"Hisab", "Mizan", "Ba'ts", "Jaza"},
            {"Hisab", "Mizan", "Ba'ts", "Jaza"},
            {"Barzakh", "Mizan", "Nyata", "Khayal"},
            //40
            {"Takir dan kehendak Allah", "Doa dan ibadah", "Kaya dan miskin", "Surga dan neraka"},
            {"Membuat mereka tidak perlu berdoa", "Membuat mereka tidak perlu bekerja", "Membantu mereka menerima apa yang terjadi dalam hidup dengan lapang dada", "Membuat mereka tidak perlu belajar"},
            {"Saat memilih makanan di restoran", "Saat menghadapi kegagalan", "Saat bermain video game", "Saat membeli baju baru"},
            {"Agar bisa menang dalam lomba", "Agar bisa menjadi kaya", "Agar bisa mendapatkan pekerjaam impian", "Agar bisa menerima dan menghadapai segala hal yang terjadi dalam hidup dengan ikhlas dan sabar"},
            {"99", "98", "100", "101"},
            {"Pengasih", "Adil", "Penyayang", "Pencipta"},
            {"Pengasih", "Adil", "Penyayang", "Pencipta"},
            {"Pengasih", "Adil", "Penyayang", "Merajai"},
            {"Bijaksana", "Adil", "Penyayang", "Merajai"},
            {"Bijaksana", "Adil", "Penyayang", "Pencipta"},
            //50
            };

    static String [] question = {
            "Ada berapa rukun Iman?",
            "Percaya kepada Allah adalah rukun Iman ke...",
            "Percaya kepada Malaikat adalah rukun Iman ke...",
            "Percaya kepada Kitab-Kitab Allah adalah rukun Iman ke...",
            "Percaya kepada Nabi dan Rasul adalah rukun Iman k...",
            "Percaya kepada Hari Akhir adalah rukun Iman ke...",
            "Percaya kepada Qada dan Qadar adalah rukun Iman ke...",
            "Ada berapa Nabi dan Rasul yang wajib kita ketahui?",
            "Berikut adalah Nabi Ulul Azmi, kecuali...",
            "Ada berapa Nabi Ulul Azmi?",
            //10
            "Ada berapa Malaikat yang wajib kita ketahui?",
            "Malaikat Jibril bertugas...",
            "Malaikat Mikail bertugas...",
            "Malaikat Israfil bertugas...",
            "Malaikat Izrail bertugas...",
            "Malaikat Munkar dan Nakir bertugas...",
            "Malaikat Raqib bertugas...",
            "Malaikat Atid bertugas...",
            "Malaikat Malik bertugas...",
            "Malaikat Ridwan bertugas...",
            //20
            "Kitab Al-Qur'an diturunkan kepada Nabi...",
            "Kitab Injil diturunkan kepada Nabi...",
            "Kitab Taurat diturunkan kepada Nabi...",
            "Kitab Zabur diturunkan kepada Nabi...",
            "Siapakah Nabi yang mendapat mukjizat dapat membelah lautan?",
            "Siapakah Nabi yang mendapat mukjizat menghidupkan orang mati?",
            "Siapakah Nabi yang mendapat mukjizat tidak dapat terbakar badannya?",
            "Siapakah Nabi yang mendapat mukjizat membelah bulan?",
            "Siapakah Nabi yang mendapat mukjizat dapat berbicara dengan hewan dan bangsa jin?",
            "Siapakah Nabi yang mendapat mukjizat dapat mengubah tongkatnya menjadi ular?",
            //30
            "Kiamat dapat dibagi menjadi kiamat sugra dan ...",
            "Berikut conoth kiamat sugra adalah, kecuali...",
            "Berikut contoh kiamat sugra...",
            "Tanda-tanda kiamat kubra adalah, kecuali...",
            "Peristiwa yang terjadi ketika kiamat kubra...",
            "Hari perhitungan amal manusia disebut yaumul...",
            "Hari dimana amal manusia ditimbang disebut yaumul...",
            "Hari pembalasan amal manusia disebut yaumul...",
            "Hari dimana seluruh manusia dibangkitkan disebut yaumul...",
            "Tempat manusia yang telah mati menunggu untuk dibangkitkan adalah alam...",
            //40
            "Apa yang dimaksud dengan Qodo dan Qodar dalam ajaran Islam?",
            "Bagaimana Qodo dan Qodar mempengaruhi kehidupan sehari-hari seorang Muslim?",
            "Contoh situasi di mana konsep Qodo dan Qodar dapat diterapkan adalah...",
            "Mengapa pemahaman tentang Qodo dan Qodar penting dalam ajaran Islam?",
            "Ada berapa jumlah asmaul husna?",
            "Ar-Rahman, artinya allah yang maha?",
            "Ar-Rahim, artinya allah yang maha?",
            "Al-Malik, artinya allah yang maha?",
            "Al-Hakim, artinya allah yang maha?",
            "Al-Adl, artinya allah yang maha?"
            //50
    };

    static String [] answer = {
            "6", "1", "2", "3", "4", "5", "6", "25", "Nabi Daud AS", "5",
            //10
            "10",
            "Menyampaikan wahyu",
            "Mengatur rezeki dan menurunkan hujan atas perintah Allah",
            "Meniup trompet sangkakala",
            "Mencabut nyawa",
            "Menanyai manusia di alam kubur",
            "Mencatat amal baik",
            "Mencatat amal buruk",
            "Menjaga Neraka",
            "Menjaga Surga",
            //20
            "Nabi Muhammad SAW",
            "Nabi Isa AS",
            "Nabi Musa AS",
            "Nabi Daud AS",
            "Nabi Musa AS",
            "Nabi Isa AS",
            "Nabi Ibrahim AS",
            "Nabi Muhammad SAW",
            "Nabi Sulaiman AS",
            "Nabi Musa AS",
            //30
            "Kiamat Kubra",
            "Keluarnya dajjal",
            "Kematian",
            "Kematian",
            "Musnahnya alam semesta",
            "Hisab",
            "Mizan",
            "Jaza",
            "Ba'ts",
            "Barzakh",
            //40
            "Takdir dan kehendak Allah",
            "Membantu mereka menerima apa yang terjadi dalam hidup dengan lapang dada",
            "Saat menghadapi kegagalan",
            "Agar bisa menerima dan menghadapi segala hal yang terjadi dalam hidup dengan sabar dan ikhlas",
            "99",
            "Pengasih",
            "Penyayang",
            "Merajai",
            "Bijaksana",
            "Adil"
    };
}
