package com.example.myjavafxquizgame;

public class SKI {
    String [][] option = {
            {"4", "5", "6", "3"},
            {"Ali bin Abi Thalib", "Abu Bakar Ash Shiddiq", "Utsman bin Affan", "Umar bin Khattab"},
            {"Ali bin Abi Thalib", "Abu Bakar Ash Shiddiq", "Utsman bin Affan", "Umar bin Khattab"},
            {"Ali bin Abi Thalib", "Abu Bakar Ash Shiddiq", "Utsman bin Affan", "Umar bin Khattab"},
            {"Ali bin Abi Thalib", "Abu Bakar Ash Shiddiq", "Utsman bin Affan", "Umar bin Khattab"},
            {"Bilal bin Rabah", "Abu Bakar Ash Shiddiq", "Utsman bin Affan", "Umar bin Khattab"},
            {"Ali bin Abi Thalib", "Abu Bakar Ash Shiddiq", "Utsman bin Affan", "Umar bin Khattab"},
            {"Amirul Mukminin", "Asbabun Nuzul", "Khulafaur Rasyidin", "Assabiqunal Awwalun"},
            {"Siti Halimah", "Khadijah", "Siti Asiyah", "Siti Fatimah"},
            {"Abdullah", "Abu Thalib", "Abu Bakar", "Abdul Muthalib"},
            //10
            {"Aminah", "Khadijah", "Siti Asiyah", "Siti Fatimah"},
            {"Abdullah", "Abu Thalib", "Abu Bakar", "Abdul Muthalib"},
            {"Abdullah", "Abu Thalib", "Abu Bakar", "Abu Muthalib"},
            {"Halimatus Sa'diyah", "Khadijah", "Siti Asiyah", "Siti Fatimah"},
            {"Ali bin Abi Thalib", "Abu Bakar Ash Shiddiq", "Zaid bin Haritsah", "Umar bin Khattab"},
            {"Gajah", "Burung", "Masehi", "Hijriah"},
            {"Muharam", "Rabiul Awal", "Rabiul Akhir", "Ramadhan"},
            {"10", "11", "12", "13"},
            {"Rabu", "Senin", "Selasa", "Jum'at"},
            {"Al-Fathah 1-7", "Al-alaq 1-5", "Al-Ikhlas 1-4", "Al-Baqarah 1-5"},
            //20
            {"Gua Hira", "Jabal Rahmah", "Gua Tsur", "Gua Haiya"},
            {"Muharam", "Rabiul Awal", "Rabiul Akhir", "Ramadhan"},
            {"3", "4", "5", "6"},
            {"Benar", "Cerdas", "Dapat dipercaya", "Menyampaikan"},
            {"Benar", "Cerdas", "Dapat dipercaya", "Menyampaikan"},
            {"Benar", "Cerdas", "Dapat dipercaya", "Menyampaikan"},
            {"Benar", "Cerdas", "Dapat dipercaya", "Menyampaikan"},
            {"Berdusta", "Bodoh", "Berkhianat", "Menyembunyikan"},
            {"Berdusta", "Bodoh", "Berkhianat", "Menyembunyikan"},
            {"Berdusta", "Bodoh", "Berkhianat", "Menyembunyikan"},
            //30
            {"Berdusta", "Bodoh", "Berkhianat", "Menyembunyikan"},
            {"5", "6", "7", "4"},
            {"Isra Mi'raj", "Puasa", "Hijrah", "Sholat"},
            {"Siang", "Pagi", "Malam", "Petang"},
            {"Masjid Quba dan Nabawi", "Masjid Nabawi dan Masjidil Haram", "Masjidil Haram dan Majidil Aqsa", "Masjidil Aqsa dan Masjid Nabawi"},
            {"Yasrib", "Madinah", "Mekkah", "Yerussalem"},
            {"Yasrib", "Madinah", "Mekkah", "Yerussalem"},
            {"Puasa", "Sholat", "Zakat", "Haji"},
            {"Isra Mi'raj", "Tahun Gajah", "Wada", "Amul Huzni"},
            {"Hijrah", "Haji", "Sai", "Isra Mi'raj"},
            //40
            {"Yasrib", "Madinah", "Mekkah", "Yerussalem"},
            {"Gua Hira", "Jabal Rahmah", "Gua Tsur", "Gua Haiya"},
            {"Kaum Anshar", "Kaum Muhajirin", "Kaum Quraisy", "Kaum Kafir"},
            {"Kaum Anshar", "Kaum Muhajirin", "Kaum Quraisy", "Kaum Kafir"},
            {"Masjid Nabawi", "Masjidil Haram", "Masjid Quba", "Masjidil Aqsa"},
            {"Yasrib", "Madinah", "Mekkah", "Yerussalem"},
            {"Yasrib", "Madinah", "Mekkah", "Yerussalem"},
            {"Pembebasan kota Madinah", "Pembebasan kota Yaman", "Pembebasan Kota Yerussalem", "Pembebasan Kota Mekkah"},
            {"Perjanjian damai antara pihak muslimin dengan pihak musyrikin yaman", "Perjanjian damai antara pihak muslimin dengan pihak musyrikin mekah", "Perjanjian damai antara pihak muslimin dengan pihak musyrikin yasrib", "Perjanjian damai antara pihak muslimin dengan pihak musyrikin madinah"},
            {"Madinah", "Syam", "Mekkah", "Yerussalem"},
            //50
            {"Menggali parit", "Menggali sumur", "Menyerang inti pertahanan", "Mengepung musuh"},
            {"Perang Badar", "Perang Shiffin", "Perang Uhud", "Perang Khandaq"},
            {"1000", "500", "314", "341"},
            {"1000", "500", "314", "341"}
    };

    String [] question = {
            "Berapa jumlah Khulafaur Rasyidin?",
            "Siapa Khulafaur Rasyidin yang pertama?",
            "Siapa Khulafaur Rasyidin yang kedua?",
            "Siapa Khulafaur Rasyidin yang ketiga?",
            "Siapa Khulafaur Rasyidin yang keempat?",
            "Berikut yang bukan Khulafaur Rasyidin adalah...",
            "Berikut ini yang termasuk orang yang pertama kali masuk dalam golongan anak-anak adalah...",
            "disebut apakah golongan orang-orang yang pertama kali memeluk agama Islam?",
            "Siapa perempuan pertama yang masuk Islam?",
            "Siapa nama ayah Nabi Muhammad SAW?",
            //10
            "Siapa nama ibu Nabi Muhammad SAW?",
            "Siapa nama kakek Nabi Muhammad SAW?",
            "Siapa nama paman Nabi Muhammad SAW?",
            "Siapa nama ibu persusuan Nabi Muhammad SAW?",
            "Siapa orang pertama dari golongan budah yang memeluk agama Islam?",
            "Nabi Muhammad SAW lahir pada tahun...",
            "Nabi Muhammad SAW lahir pada bulan...",
            "Nabi Muhammad SAW lahir pada tanggal ... Rabiul Awal",
            "Nabi Muhammad SAW lahir pada hari...",
            "Wahyu pertama yang diturunkan adalah...",
            //20
            "Dimana wahyu pertama diturunkan?",
            "Al-Qur'an diturunkan pertama kali pada bulan...",
            "Ada berapa sifat yang wajib dimiliki rasul?",
            "Siddiq artinya...",
            "Amanah artinya...",
            "Tabligh artinya...",
            "Fathonah artinya...",
            "kidzib artinya...",
            "Baladah artinya...",
            "Kitman artinya...",
            //30
            "Khianah artinya...",
            "Ada berapa sifat mustahil yang dimiliki Rasul?",
            "Perjalanan Nabi Muhammad SAW dari masjidil haram ke masjidil aqsa kemudian naik ke sidratul Muntaha adalah pengertian dari...",
            "Isra mi’raj adalah perjalanan yang dilakukkan pada waktu ... hari",
            "Masjid yang di singgahi saat Isra Mi’raj adalah...",
            "Masjidil Haram terletak di kota...",
            "Masjidil Aqsa terletak di kota...",
            "Saat peristiwa Isra Mi’raj Rasulullah mendapatkan perintah untuk menjalankan ibadah...",
            "Tahun kesedihan yang dialami Rasulullah SAW disebut...",
            "Perpindahan dari suatu tempat ke menuju tempat yang lebih baik disebut...",
            //40
            "Nabi Muhammad SAW hijrah dari mekkah ke...",
            "Nabi Muhammad SAW sempat bersembunyi di ... saat perjalanan hijrah",
            "Sahabat yang hijrah dari Mekkah ke Madinah disebut...",
            "Sahabat yang tinggal di Madinah disebut...",
            "Masjid pertama yang dibangun oleh Nabi Muhammad SAW adalah...",
            "Nabi Muhammad SAW dilahirkan di kota...",
            "Nabi Muhammad SAW wafat di kota...",
            "Apa arti dari Fathu Makkah?",
            "Apa arti dari Perjanjian Hudaibiyah?",
            "Yasrib adalah nama lain dari kota...",
            //50
            "Perang Khandaq memiliki arti perang dengan strategi...",
            "Perang pertama kaum Muslimin melawan Kaum Kafir adalah...",
            "Jumlah pasukan kaum muslimin dalam perang badar adalah...",
            "Berapa jumlah pasukan kaum kafir quraisy dalam perang badar?"
    };

    String [] answer = {
            "4",
            "Abu Bakar Ash Shiddiq",
            "Umar bin Khattab",
            "Utsman bin Affan",
            "Ali bin Abi Thalib",
            "Bilal bin Rabah",
            "Ali bin Abi Thalib",
            "Assabiqunal Awwalun",
            "Khadijah",
            "Abdullah",
            //10
            "Aminah",
            "Abdul Muthalib",
            "Abu Thalib",
            "Halimatus Sa'diyah",
            "Zaid bin Haritsah",
            "Gajah",
            "Rabiul Awal",
            "12",
            "Senin",
            "Al Alaq 1-5",
            //20
            "Gua Hira",
            "Ramadhan",
            "4",
            "Benar",
            "Dapat dipercaya",
            "Menyampaikan",
            "Cerdas",
            "Berdusta",
            "Bodoh",
            "Menyembunyikan",
            //30
            "Berkhianat",
            "4",
            "Isra Mi'raj",
            "Malam",
            "Masjidil haram dan Masjidil Aqsa",
            "Mekkah",
            "Yerussalem",
            "Sholat",
            "Amul Huzni",
            "Hijrah",
            //40
            "Yasrib",
            "Gua Tsur",
            "Kaum Muhajirin",
            "Kaum Anshar",
            "Masjid Quba",
            "Mekkah",
            "Madinah",
            "Pembebasan kota Mekkah",
            "Perjanjian damai antara pihak muslimin dengan pihak musyrikin mekah",
            "Madinah",
            //50
            "Menggali parit",
            "Perang badar",
            "314",
            "1000"
    };
}
