package com.example.myjavafxquizgame;

public class Tahsin {
    static String [][] option = {
            {"1", "2", "3", "4"},
            {"28", "25", "30", "26"},
            {"A", "E", "U", "I"},
            {"A", "E", "U", "I"},
            {"A", "E", "U", "I"},
            {"Jelas", "Mengganti", "Masuk", "Samar"},
            {"Jelas", "Mengganti", "Masuk", "Samar"},
            {"Jelas", "Mengganti", "Masuk", "Samar"},
            {"Jelas", "Mengganti", "Masuk", "Samar"},
            {"Bighunnah dan Bilaghunnah", "Bighunnah dan Ghunnah", "Bilaghunnah dan Ghunnah", "Bilaghennah dan Bighunnah"},
            //10
            {"Izhar", "Idgham bighunnah", "Idgham bilaghunnah", "Ikhfa"},
            {"Izhar", "Idgham bighunnah", "Idgham bilaghunnah", "Ikhfa"},
            {"Dibaca jelas, dengan dengung", "Dengung tetapi jelas", "Masuk dengan tak dengung", "Dibaca jelas, tidak berdengung"},
            {"3", "4", "5", "6"},
            {"Idzhar", "Iqlab", "Idgham", "Ikhfa"},
            {"5", "10", "15", "20"},
            {"Idzhar", "Iqlab", "Idgham", "Ikhfa"},
            {"Idzhar", "Iqlab", "Idgham", "Ikhfa"},
            {"Idzhar syafawi", "Idgham mutaqaribin", "Idgham mimi", "Ikhfa syafawi"},
            {"Idzhar syafawi", "Idgham mutamatsilain", "Idgham mimi", "Ikhfa syafawi"},
            //20
            {"Idzhar syafawi", "Idgham mutaqaribin", "Idgham mimi", "Ikhfa syafawi"},
            {"Idzhar syafawi", "Idgham mutaqaribin", "Idgham mimi", "Ikhfa syafawi"},
            {"Dengung", "Sembunyi", "Terang", "Samar"},
            {"Idzhar syafawi", "Idgham mutaqaribin", "Idgham dengan ghunnah", "Ikhfa syafawi"},
            {"2, 4", "2, 3", "1, 2", "4, 5"},
            {"Makharizul Lisani", "Makharizul Huruf", "Makharizul Syafatain", "Makharizul Halq"},
            {"Tebal dan Tafkhim", "Tipis dan Tarqiq", "Tebal dan Tipis", "Tebal dan Ithbaq"},
            {"Tafkhim", "Tarqiq", "Isti'la", "Ithbaq"},
            {"Tafkhim", "Tarqiq", "Isti'la", "Ithbaq"},
            {"Tebal dan Tafkhim", "Tipis dan Tarqiq", "Tebal dan Tipis", "Isti'la dan Ithbaq"},
            //30
            {"Memantul", "Membalik", "Gema", "Jelas"},
            {"Tafkhim dan Tarqiq", "Sugra dan Kubra", "Tafkhim dan Sugra", "Tarqiq dan Kubra"},
            {"Kecil", "Tebal", "Tipis", "Besar"},
            {"Kecil", "Tebal", "Tipis", "Besar"},
            {"Imalah", "Isymam", "Saktah", "Naqlun"},
            {"Imalah", "Isymam", "Saktah", "Naqlun"},
            {"Fardhu 'Ain", "Fardhu Kifayah", "Sunnah Muakkad", "Sunnah"},
            {"Panjang pendek", "Bacaan panjang", "Bacaan pendek", "Cara baca"},
            {"1", "3", "4", "2"},
            {"Mad wajib mutashil", "Mad jaiz munfasil", "Mad lazim kilmi mutsaqqal", "Mad farq"},
            //40
            {"Mad wajib mutashil", "Mad jaiz munfasil", "Mad lazim kilmi mutsaqqal", "Mad farq"},
            {"Mad wajib mutashil", "Mad jaiz munfasil", "Mad lazim kilmi mutsaqqal", "Mad farq"},
            {"Mad wajib mutashil", "Mad jaiz munfasil", "Mad lazim kilmi mutsaqqal", "Mad farq"},
            {"Mad badal", "Mad 'iwad", "Mad layyn", "Mad farq"},
            {"Mad badal", "Mad 'iwad", "Mad layyn", "Mad farq"},
            {"Mad badal", "Mad 'iwad", "Mad layyn", "Mad farq"},
            {"10", "15", "20", "25"},
            {"5", "6", "4", "3"},
            {"Tanwin", "Sukun", "Tasydid", "Idgham"},
            {"Basmalah", "Ta'awudz", "Hamdalah", "Dzikir"},
            //50
            };

    static String [] question = {
            "Satu alif sama dengan ... harakat",
            "Ada berapa huruf hijaiyah?",
            "Ketika suatu huruf berharakat fathah, maka huruf tersebut dibaca dengan vokal...",
            "Ketika suatu huruf berharakat kasrah, maka huruf tersebut dibaca dengan vokal...",
            "Ketika suatu huruf berharakat dammah, maka huruf tersebut dibaca dengan vokal...",
            "Idzhar berarti...",
            "Idgham berarti...",
            "Iqlab berarti...",
            "Ikhfa berarti...",
            "Idgham dalam hukum nun mati terbagi menjadi dua, yaitu...",
            //10
            "Masuk dengan dengung selama 2 harakat adalah bunyi hukum...",
            "Masuk dengan tak dengung adalah bunyi hukum...",
            "Cara membaca idzhar adalah...",
            "Secara pembagian besar, hukum nun mati/tanwin terbagi menjadi...",
            "Nun mati atau tanwin bila bertemu huruf ba suaranya berubah menjadi mim sukun dengan dengung selama 2 harakat, adalah bunyi hukum...",
            "Ada berapa jumlah huruf ikhfa’?",
            "Nun mati atau tanwin dibaca samar-samar jika bertemu dengan salah satu dari 15 huruf hijaiyah, dengan dengung selama 2 harakat adalah bunyi hukum...",
            "Berikut yang bukan hukum mim mati adalah...",
            "Mim mati bertemu mim dibaca masuk dengan dengung adalah bunyi hukum...",
            "Semua huruf yang disukun bertemu dengan huruf berharakat yang sama/semisal di hadapannya adalah bunyi hukum...",
            //20
            "Mim mati bertemu huruf ba dibaca samar-samar dengan dengung adalah bunyi hukum...",
            "Mim mati bertemu huruf selian ba dan mim dibaca jelas adalah bunyi hukum...",
            "Ghunnah adalah...",
            "Setiap huruf mim dan nun bertasydid, maka hukum bacaannya adalah...",
            "Setiap huruf mim dan nun bertasydid, maka hukum bacaannya adalah idgham dengan ghunnah selama ... atau ... harakat",
            "Tempat keluarnya huruf disebut...",
            "Sifat huruf hijaiyah dapat dibagi menjadi 2, yaitu...",
            "Sifat huruf hijaiyah tebal disebut juga...",
            "Sifat huruf hijaiyah tipis disebut juga...",
            "Sifat huruf hijaiyah tebal bisa dibagi lagi menjadi dua, yaitu...",
            //30
            "Qalqalah berarti...",
            "Qalqalah terbagi menjadi dua, yaitu...",
            "Qalqalah sugra dibaca dengan pantualan yang lebih...",
            "Qalqalah kubra dibaca dengan pantualan yang lebih...",
            "Bacaan antara fathah dan kasroh seperti suara E kata sate adalah pengertian dari hukum bacaan ...",
            "Berhenti selama dua harakat dan tidak bernapas disebut dengan hukum bacaan ...",
            "Hukum mempelajari ilmu tajwid adalah ...",
            "Mad berarti...",
            "Mad thabi’i dibaca panjang ... harakat",
            "Bertemu huruf mad dengan hamzah dalam satu kata dan dibaca panjang 4-5 harakat adalah bunyi hukum bacaan...",
            //40
            "Bertemu huruf mad dengan hamzah berharakat di suatu kata lain dan dibaca panjang 2/4/6 harakat adalah bunyi hukum bacaan...",
            "Bertemu huruf mad dengan huruf bertasydid dalam satu kata dan dibaca panjang 6 harakat adalah bunyi hukum bacaan...",
            "Bertemunya 2 hamzah dan dibaca panjang 6 harakat adalah bunyi hukum bacaan...",
            "Pengganti dari huruf yang semula hamzah sukun yang ada di hadapannya dan dibaca panjang 2 harakat adalah bunyi hukum bacaan...",
            "Pengganti fathah tanwin ketika diwaqofkan dengan membaca fahah saja dan dibaca panjang 2 harakat adalah bunyi hukum bacaan...",
            "Waw sukun atau ya sukun yang didahului fathah dan dibaca lunak dengan panjang 2 harakat adalah bunyi hukum bacaan...",
            "Pada hukum nun mati atau tanwin, ada berapa huruf ikhfa’...",
            "Ada berapa huruf qalqalah...",
            "Berikut yang tidak termasuk tanda baca atau harakat adalah...",
            "Sebelum membaca Al-Qur’an kita diperintahkan untuk berlindung dari godaan syaitan, maksudnya membaca..."
            //50
    };

    static String [] answer = {
            "2", "30", "A", "I", "U", "Jelas", "Masuk", "Mengganti", "Samar", "Bighunnah dan Bilaghunnah",
            //10
            "Idgham bighunnah",
            "Idgham bilaghunnah",
            "Dibaca jelas, tidak berdengung",
            "4",
            "Iqlab",
            "15",
            "Ikhfa",
            "Iqlab",
            "Idgham mimi",
            "Idhgam mutamatsilain",
            //20
            "Ikhfa syafawi",
            "Idzhar syafawi",
            "Dengung",
            "Idgham dengan ghunnah",
            "2, 3",
            "Makharizul Huruf",
            "Tebal dan tipis",
            "Tafkhim",
            "Tarqiq",
            "Isti’la dan Ithbaq",
            //30
            "Memantul",
            "Sugra dan Kubra",
            "Kecil",
            "Besar",
            "Imalah",
            "Saktah",
            "Fardhu Kifayah",
            "Bacaan panjang",
            "2",
            "Mad wajib mutashil",
            //40
            "Mad jaiz munfasil",
            "Mad lazim kilmi mutsaqqal",
            "Mad farq",
            "Mad badal",
            "Mad 'iwad",
            "Mad layyn",
            "15",
            "5",
            "Idgham",
            "Ta'awudz"
    };
}
